### ISSUE TITLE
shitty bug through shitty meal info by studentenwerk

### ISSUE THREAD

**Issue by whosFritz** [whosFritz/Mensa-App#32]
jeeeeez, every time i think the mensa studentenwerk schedule can't get any worse, it get's worse
i got an algorithm that fixes the Pastateller bug, Spaghetti dish gets separated in 3 dishes (cheese, sauce and pasta type).
but cause the data from studentenwerk is shit, there are false information

**Comment by greybaron** [comment]
[My Pei$$en-based crawler ](https://github.com/greybaron/StuWeLeipzig-Mensa-TelegramBot/blob/a53325da6be7e6f31dba12bcc37ddbe743c8f144/bot.py#L272) supports this scenario. Maybe that is helpful.

**Comment by olech2412** [comment]
The problem should be solved in the GUI of the program or by the Studentenwerk Leipzig. Since nothing can be expected from the Studentenwerk, it has to be solved on the surface. This problem is actually only about the presentation of the data because the storage of the data is correct. Otherwise you could not assign a dish to which category it belongs. 

Example:
![image](https://user-images.githubusercontent.com/76694468/217192114-b5fa476a-2451-4315-8130-a782a2c3d26c.png)
Unfortunately, the OG Peissen crawler cant help us

**Comment by whosFritz** [comment]
Can be closed cause of expansion panel list solution
